api_platform:
    title: 'Brand management APIs'
    description: 'CRUD API operations for managing a top list of brands'
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
