nelmio_api_doc:
    documentation:
        info:
            title: 'Brand management APIs'
            description: 'CRUD API operations for managing a top list of brands'
            version: 1.0.0
    areas: # to filter documented areas
        # default:
            # path_patterns: [ '^/api' ]
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
